FROM odoo:latest

ARG GROUP_GID=101
ARG USER_UID=1000
ENV USER_NAME=root
ENV PROJECT_DIR=/home/odoo_project
ENV LANG=C.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=C.UTF-8

USER $USER_NAME

WORKDIR $PROJECT_DIR

RUN mkdir -p $PROJECT_DIR

COPY --chown=$USER_NAME . $PROJECT_DIR